// 漢字クエスト — 問題バンク (Question bank)
// Each question:
//   s: sentence with {target} highlighted.
//      Non-target kanji words use 漢字[よみ] notation → rendered as <ruby> furigana.
//      The {target} itself never gets furigana (it would reveal the answer).
//   target: the word being asked about
//   ans: correct answer
//   opts: 4 options (correct + 3 distractors)
//   reverse: true => kana shown, choose kanji; false => kanji shown, choose reading
//   level: "N4" or "N3"
//   meaning: English gloss for review / meaning mode

const QUESTIONS = [
  // ===================== N4 =====================
  { level:"N4", s:"来週[らいしゅう]、駅[えき]の近[ちか]くで友達[ともだち]に{会います}。", target:"会います", ans:"あいます", opts:["あいます","あります","かいます","おいます"], reverse:false, meaning:"to meet" },
  { level:"N4", s:"兄[あに]と私[わたし]は{同じ}学校[がっこう]に通[かよ]っています。", target:"同じ", ans:"おなじ", opts:["おなじ","どうじ","おなし","おおじ"], reverse:false, meaning:"same" },
  { level:"N4", s:"その{事}については後[あと]で話[はな]しましょう。", target:"事", ans:"こと", opts:["こと","もの","じ","わけ"], reverse:false, meaning:"matter, thing" },
  { level:"N4", s:"彼[かれ]は{自分}で全部[ぜんぶ]やりました。", target:"自分", ans:"じぶん", opts:["じぶん","じふん","しぶん","じっぷん"], reverse:false, meaning:"oneself" },
  { level:"N4", s:"父[ちち]は大[おお]きな{会社}で働[はたら]いています。", target:"会社", ans:"かいしゃ", opts:["かいしゃ","かいしゃう","がいしゃ","かいじゃ"], reverse:false, meaning:"company" },
  { level:"N4", s:"新[あたら]しい商品[しょうひん]が来月[らいげつ]{発売}されます。", target:"発売", ans:"はつばい", opts:["はつばい","はっぱい","はつうり","はつまい"], reverse:false, meaning:"release, sale" },
  { level:"N4", s:"この{地図}を見[み]れば道[みち]が分[わ]かります。", target:"地図", ans:"ちず", opts:["ちず","じず","ちと","ちほう"], reverse:false, meaning:"map" },
  { level:"N4", s:"仕事[しごと]の{方法}を先輩[せんぱい]に教[おそ]わりました。", target:"方法", ans:"ほうほう", opts:["ほうほう","ほうぼう","ほうこう","ほうしき"], reverse:false, meaning:"method" },
  { level:"N4", s:"{新しい}パソコンを買[か]うつもりです。", target:"新しい", ans:"あたらしい", opts:["あたらしい","めずらしい","あたたかい","うつくしい"], reverse:false, meaning:"new" },
  { level:"N4", s:"駅前[えきまえ]の{場所}で待[ま]ち合[あ]わせしましょう。", target:"場所", ans:"ばしょ", opts:["ばしょ","ばあいしょ","じょうしょ","ばじょ"], reverse:false, meaning:"place" },
  { level:"N4", s:"会議[かいぎ]で新[あたら]しい{問題}が出[で]ました。", target:"問題", ans:"もんだい", opts:["もんだい","もんたい","ぶんだい","といだい"], reverse:false, meaning:"problem" },
  { level:"N4", s:"部屋[へや]がとても{明るい}ですね。", target:"明るい", ans:"あかるい", opts:["あかるい","あきるい","めいるい","あけるい"], reverse:false, meaning:"bright" },
  { level:"N4", s:"この機械[きかい]は音[おと]もなく{動く}。", target:"動く", ans:"うごく", opts:["うごく","どうく","うこく","はたらく"], reverse:false, meaning:"to move" },
  { level:"N4", s:"来年[らいねん]、京都[きょうと]へ{旅行}に行[い]きたいです。", target:"旅行", ans:"りょこう", opts:["りょこう","りょうこう","りょこ","たびこう"], reverse:false, meaning:"trip, travel" },
  { level:"N4", s:"毎朝[まいあさ]、公園[こうえん]の周[まわ]りを{歩いて}います。", target:"歩いて", ans:"あるいて", opts:["あるいて","はしいて","あゆいて","ほいて"], reverse:false, meaning:"to walk" },
  { level:"N4", s:"わからないことは先生[せんせい]に{質問}します。", target:"質問", ans:"しつもん", opts:["しつもん","しちもん","しつぶん","じつもん"], reverse:false, meaning:"question" },
  { level:"N4", s:"友達[ともだち]を家[いえ]に{招待}しました。", target:"招待", ans:"しょうたい", opts:["しょうたい","しょうだい","そうたい","しょたい"], reverse:false, meaning:"invitation" },
  { level:"N4", s:"駅前[えきまえ]に人[ひと]がたくさん{集まって}いた。", target:"集まって", ans:"あつまって", opts:["あつまって","しゅうまって","あつめって","つよまって"], reverse:false, meaning:"to gather" },
  { level:"N4", s:"今日[きょう]は朝[あさ]から{忙しい}一日[いちにち]でした。", target:"忙しい", ans:"いそがしい", opts:["いそがしい","ぼうがしい","むずかしい","うれしい"], reverse:false, meaning:"busy" },
  { level:"N4", s:"夏休[なつやす]みに海[うみ]で{泳ぎ}たいです。", target:"泳ぎ", ans:"およぎ", opts:["およぎ","えいぎ","おおぎ","うみぎ"], reverse:false, meaning:"to swim" },
  { level:"N4", s:"私[わたし]は日本[にほん]の{音楽}をよく聞[き]きます。", target:"音楽", ans:"おんがく", opts:["おんがく","おんらく","おとがく","いんがく"], reverse:false, meaning:"music" },
  { level:"N4", s:"母[はは]は{料理}がとても上手[じょうず]です。", target:"料理", ans:"りょうり", opts:["りょうり","りょり","れいり","りょうに"], reverse:false, meaning:"cooking" },
  { level:"N4", s:"{銀行}でお金[かね]を下[お]ろしました。", target:"銀行", ans:"ぎんこう", opts:["ぎんこう","ぎんぎょう","きんこう","ぎんこ"], reverse:false, meaning:"bank" },
  { level:"N4", s:"熱[ねつ]があるので{病院}へ行[い]きます。", target:"病院", ans:"びょういん", opts:["びょういん","びよういん","びょうえん","べういん"], reverse:false, meaning:"hospital" },
  { level:"N4", s:"週末[しゅうまつ]に友達[ともだち]と{映画}を見[み]ました。", target:"映画", ans:"えいが", opts:["えいが","えが","えいか","ようが"], reverse:false, meaning:"movie" },
  { level:"N4", s:"駅[えき]の近[ちか]くで{買い物}をしました。", target:"買い物", ans:"かいもの", opts:["かいもの","ばいもの","かいぶつ","こうもの"], reverse:false, meaning:"shopping" },
  { level:"N4", s:"明日[あした]の{天気}は雨[あめ]だそうです。", target:"天気", ans:"てんき", opts:["てんき","てんち","でんき","てんけ"], reverse:false, meaning:"weather" },
  { level:"N4", s:"週末[しゅうまつ]は{図書館}で勉強[べんきょう]します。", target:"図書館", ans:"としょかん", opts:["としょかん","ずしょかん","としょうかん","とかん"], reverse:false, meaning:"library" },
  { level:"N4", s:"{特急}に乗[の]れば早[はや]く着[つ]きます。", target:"特急", ans:"とっきゅう", opts:["とっきゅう","とくきゅう","とっきゅ","どっきゅう"], reverse:false, meaning:"limited express" },
  { level:"N4", s:"私[わたし]は三人[さんにん]{兄弟}です。", target:"兄弟", ans:"きょうだい", opts:["きょうだい","けいだい","きょだい","けいてい"], reverse:false, meaning:"siblings" },
  { level:"N4", s:"母[はは]は{台所}で夕飯[ゆうはん]を作[つく]っています。", target:"台所", ans:"だいどころ", opts:["だいどころ","たいしょ","だいところ","たいどころ"], reverse:false, meaning:"kitchen" },
  { level:"N4", s:"この店[みせ]の{品物}は安[やす]くていい。", target:"品物", ans:"しなもの", opts:["しなもの","ひんもの","しなぶつ","ほんもの"], reverse:false, meaning:"goods" },
  { level:"N4", s:"父[ちち]は車[くるま]の{運転}が上手[じょうず]です。", target:"運転", ans:"うんてん", opts:["うんてん","うんでん","うんそう","こうてん"], reverse:false, meaning:"driving" },
  { level:"N4", s:"いつか{世界}を旅[たび]したいです。", target:"世界", ans:"せかい", opts:["せかい","せいかい","せけい","しかい"], reverse:false, meaning:"world" },
  { level:"N4", s:"{授業}は九時[くじ]に始[はじ]まります。", target:"授業", ans:"じゅぎょう", opts:["じゅぎょう","じゅうぎょう","しゅぎょう","じゅげい"], reverse:false, meaning:"class, lesson" },
  { level:"N4", s:"デパートの{屋上}から町[まち]が見[み]えます。", target:"屋上", ans:"おくじょう", opts:["おくじょう","やじょう","おくうえ","やうえ"], reverse:false, meaning:"rooftop" },
  { level:"N4", s:"今日[きょう]は{気分}がいいです。", target:"気分", ans:"きぶん", opts:["きぶん","きふん","けぶん","きもち"], reverse:false, meaning:"mood, feeling" },
  { level:"N4", s:"時間[じかん]がないので{急いで}ください。", target:"急いで", ans:"いそいで", opts:["いそいで","きゅういで","いついで","およいで"], reverse:false, meaning:"to hurry" },
  { level:"N4", s:"明日[あした]、荷物[にもつ]を{送ります}。", target:"送ります", ans:"おくります", opts:["おくります","そうります","おくれます","はこびます"], reverse:false, meaning:"to send" },
  { level:"N4", s:"ペンを{貸して}ください。", target:"貸して", ans:"かして", opts:["かして","たいして","かりて","はして"], reverse:false, meaning:"to lend" },
  { level:"N4", s:"ピアノを{習って}います。", target:"習って", ans:"ならって", opts:["ならって","しゅうって","なれって","まなって"], reverse:false, meaning:"to learn" },
  { level:"N4", s:"毎朝[まいあさ]六時[ろくじ]に{起きます}。", target:"起きます", ans:"おきます", opts:["おきます","きます","たちます","あきます"], reverse:false, meaning:"to wake up" },
  { level:"N4", s:"弟[おとうと]は背[せ]が{低い}です。", target:"低い", ans:"ひくい", opts:["ひくい","てくい","やすい","みじかい"], reverse:false, meaning:"low, short" },
  { level:"N4", s:"夜[よる]の道[みち]は{暗い}ので気[き]をつけて。", target:"暗い", ans:"くらい", opts:["くらい","あんい","くろい","こわい"], reverse:false, meaning:"dark" },
  { level:"N4", s:"このかばんはとても{重い}です。", target:"重い", ans:"おもい", opts:["おもい","かさい","じゅうい","おそい"], reverse:false, meaning:"heavy" },
  { level:"N4", s:"新[あたら]しいパソコンは{軽い}です。", target:"軽い", ans:"かるい", opts:["かるい","けいい","かろい","やすい"], reverse:false, meaning:"light (weight)" },
  { level:"N4", s:"早[はや]く{医者}に行[い]った方[ほう]がいいですよ。", target:"医者", ans:"いしゃ", opts:["いしゃ","いしや","いじゃ","いちゃ"], reverse:false, meaning:"doctor" },
  { level:"N4", s:"{店員}に値段[ねだん]を聞[き]きました。", target:"店員", ans:"てんいん", opts:["てんいん","てんにん","でんいん","てにん"], reverse:false, meaning:"shop clerk" },
  { level:"N4", s:"暑[あつ]いので窓[まど]を{開けて}ください。", target:"開けて", ans:"あけて", opts:["あけて","ひらけて","かけて","さけて"], reverse:false, meaning:"to open" },
  { level:"N4", s:"友達[ともだち]に{手紙}を書[か]きました。", target:"手紙", ans:"てがみ", opts:["てがみ","てかみ","しゅがみ","てし"], reverse:false, meaning:"letter" },
  { level:"N4", s:"父[ちち]の{代わり}に私[わたし]が行[い]きます。", target:"代わり", ans:"かわり", opts:["かわり","だいわり","よわり","かえり"], reverse:false, meaning:"substitute, instead" },
  { level:"N4", s:"{東京}は人[ひと]がとても多[おお]い。", target:"東京", ans:"とうきょう", opts:["とうきょう","ときょう","とうきょ","どうきょう"], reverse:false, meaning:"Tokyo" },
  { level:"N4", s:"パソコンの使[つか]いすぎで{目}が疲[つか]れた。", target:"目", ans:"め", opts:["め","もく","まなこ","ひとみ"], reverse:false, meaning:"eye" },
  { level:"N4", s:"妹[いもうと]は大学[だいがく]に{通って}います。", target:"通って", ans:"かよって", opts:["かよって","とおって","つうじて","つうって"], reverse:false, meaning:"to commute" },
  { level:"N4", s:"新[あたら]しい{言葉}を覚[おぼ]えました。", target:"言葉", ans:"ことば", opts:["ことば","いいば","げんば","ことのは"], reverse:false, meaning:"word, language" },
  { level:"N4", s:"{体}の調子[ちょうし]がいいです。", target:"体", ans:"からだ", opts:["からだ","たいだ","かたち","こころ"], reverse:false, meaning:"body" },
  { level:"N4", s:"この店[みせ]は{主に}若[わか]い人[ひと]が来[く]る。", target:"主に", ans:"おもに", opts:["おもに","しゅに","ぬしに","まもに"], reverse:false, meaning:"mainly" },
  { level:"N4", s:"この町[まち]は電車[でんしゃ]がなくて{不便}です。", target:"不便", ans:"ふべん", opts:["ふべん","ぶべん","ふびん","ふへん"], reverse:false, meaning:"inconvenient" },
  { level:"N4", s:"日本語[にほんご]で{作文}を書[か]きました。", target:"作文", ans:"さくぶん", opts:["さくぶん","さぶん","つくぶん","さくもん"], reverse:false, meaning:"essay, composition" },
  { level:"N4", s:"もう{一度}言[い]ってください。", target:"一度", ans:"いちど", opts:["いちど","いっど","いちたび","いちどう"], reverse:false, meaning:"once, one time" },
  { level:"N4", s:"子供[こども]たちが{公園}で遊[あそ]んでいる。", target:"公園", ans:"こうえん", opts:["こうえん","こうえ","くえん","こうねん"], reverse:false, meaning:"park" },
  { level:"N4", s:"傘[かさ]を{持って}行[い]きなさい。", target:"持って", ans:"もって", opts:["もって","じって","まって","たもって"], reverse:false, meaning:"to hold, carry" },
  { level:"N4", s:"{野菜}をもっと食[た]べましょう。", target:"野菜", ans:"やさい", opts:["やさい","のさい","やざい","やせい"], reverse:false, meaning:"vegetables" },
  { level:"N4", s:"三十分[さんじゅっぷん]{以上}待[ま]ちました。", target:"以上", ans:"いじょう", opts:["いじょう","いうえ","いしょう","いじょ"], reverse:false, meaning:"more than" },
  { level:"N4", s:"旅行[りょこう]のいい{思い出}ができた。", target:"思い出", ans:"おもいで", opts:["おもいで","おもいだし","しゅつ","おもで"], reverse:false, meaning:"memory" },
  { level:"N4", s:"{多分}明日[あした]は雨[あめ]でしょう。", target:"多分", ans:"たぶん", opts:["たぶん","おおぶん","たふん","だぶん"], reverse:false, meaning:"probably" },
  { level:"N4", s:"{正しい}答[こた]えを選[えら]んでください。", target:"正しい", ans:"ただしい", opts:["ただしい","せいしい","まさしい","やさしい"], reverse:false, meaning:"correct" },
  { level:"N4", s:"連絡[れんらく]をもらって{安心}した。", target:"安心", ans:"あんしん", opts:["あんしん","やすしん","あんじん","あんこころ"], reverse:false, meaning:"relief" },
  { level:"N4", s:"駅[えき]への道[みち]を{教えて}ください。", target:"教えて", ans:"おしえて", opts:["おしえて","きょうえて","おそわえて","しえて"], reverse:false, meaning:"to tell, teach" },
  { level:"N4", s:"おかげさまで{元気}です。", target:"元気", ans:"げんき", opts:["げんき","がんき","もとき","げんけ"], reverse:false, meaning:"healthy, energetic" },
  { level:"N4", s:"何[なに]かいい{考え}はありませんか。", target:"考え", ans:"かんがえ", opts:["かんがえ","こうがえ","かんげえ","しんがえ"], reverse:false, meaning:"idea, thought" },
  { level:"N4", s:"{海}の近[ちか]くのホテルに泊[と]まった。", target:"海", ans:"うみ", opts:["うみ","かい","なみ","みずうみ"], reverse:false, meaning:"sea" },
  { level:"N4", s:"その話[はなし]はもう{知って}います。", target:"知って", ans:"しって", opts:["しって","ちって","わかって","しんって"], reverse:false, meaning:"to know" },
  { level:"N4", s:"{別に}問題[もんだい]はありません。", target:"別に", ans:"べつに", opts:["べつに","わかれに","べちに","へつに"], reverse:false, meaning:"(not) particularly" },
  { level:"N4", s:"この辞書[じしょ]を{使って}もいいですか。", target:"使って", ans:"つかって", opts:["つかって","しって","つかれて","ちかって"], reverse:false, meaning:"to use" },
  { level:"N4", s:"{時計}が止[と]まっています。", target:"時計", ans:"とけい", opts:["とけい","じけい","ときい","とっけい"], reverse:false, meaning:"clock, watch" },
  { level:"N4", s:"飼[か]っていた金魚[きんぎょ]が{死んで}しまった。", target:"死んで", ans:"しんで", opts:["しんで","じんで","しねで","すんで"], reverse:false, meaning:"to die" },
  { level:"N4", s:"{特に}漢字[かんじ]の勉強[べんきょう]が大変[たいへん]だ。", target:"特に", ans:"とくに", opts:["とくに","どくに","とくべつに","ときに"], reverse:false, meaning:"especially" },
  { level:"N4", s:"映画[えいが]は七時[しちじ]に{始まります}。", target:"始まります", ans:"はじまります", opts:["はじまります","しまります","はしまります","ひらまります"], reverse:false, meaning:"to begin" },
  { level:"N4", s:"{朝ご飯}を食[た]べましたか。", target:"朝ご飯", ans:"あさごはん", opts:["あさごはん","あさごめし","ちょうごはん","あさはん"], reverse:false, meaning:"breakfast" },
  { level:"N4", s:"仕事[しごと]が{終わったら}、電話[でんわ]します。", target:"終わったら", ans:"おわったら", opts:["おわったら","しゅうわったら","とわったら","かわったら"], reverse:false, meaning:"to finish" },
  { level:"N4", s:"この部屋[へや]は{広い}ですね。", target:"広い", ans:"ひろい", opts:["ひろい","こうい","ひらい","ふかい"], reverse:false, meaning:"spacious, wide" },
  { level:"N4", s:"兄[あに]は大阪[おおさか]に{住んで}います。", target:"住んで", ans:"すんで", opts:["すんで","じゅんで","しんで","すみんで"], reverse:false, meaning:"to live, reside" },
  { level:"N4", s:"{無理}をしないでください。", target:"無理", ans:"むり", opts:["むり","ぶり","むぎ","なり"], reverse:false, meaning:"impossible, overdoing" },
  { level:"N4", s:"ここで{写真}を撮[と]ってもいいですか。", target:"写真", ans:"しゃしん", opts:["しゃしん","しゃじん","さしん","しゃっしん"], reverse:false, meaning:"photograph" },
  { level:"N4", s:"この店[みせ]はラーメンで{有名}です。", target:"有名", ans:"ゆうめい", opts:["ゆうめい","うめい","ゆめい","ゆうな"], reverse:false, meaning:"famous" },
  { level:"N4", s:"駅[えき]の{出口}で待[ま]っています。", target:"出口", ans:"でぐち", opts:["でぐち","しゅっこう","だしぐち","でくち"], reverse:false, meaning:"exit" },
  { level:"N4", s:"もう{少し}ゆっくり話[はな]してください。", target:"少し", ans:"すこし", opts:["すこし","しょうし","すくし","ちいさし"], reverse:false, meaning:"a little" },
  { level:"N4", s:"静[しず]かな{町}に住[す]みたい。", target:"町", ans:"まち", opts:["まち","ちょう","むら","みやこ"], reverse:false, meaning:"town" },
  { level:"N4", s:"父[ちち]は{工場}で働[はたら]いています。", target:"工場", ans:"こうじょう", opts:["こうじょう","くじょう","こうじょ","ごうじょう"], reverse:false, meaning:"factory" },
  { level:"N4", s:"あの白[しろ]い{建物}は図書館[としょかん]です。", target:"建物", ans:"たてもの", opts:["たてもの","けんぶつ","たちもの","けんもの"], reverse:false, meaning:"building" },
  { level:"N4", s:"{空}が青[あお]くて気持[きも]ちがいい。", target:"空", ans:"そら", opts:["そら","くう","から","かぜ"], reverse:false, meaning:"sky" },
  { level:"N4", s:"急[きゅう]に車[くるま]が{止まって}驚[おどろ]いた。", target:"止まって", ans:"とまって", opts:["とまって","しまって","やまって","とどまって"], reverse:false, meaning:"to stop" },
  { level:"N4", s:"{大切}な書類[しょるい]をなくしてしまった。", target:"大切", ans:"たいせつ", opts:["たいせつ","だいせつ","たいきり","おおぎり"], reverse:false, meaning:"important, precious" },
  { level:"N4", s:"{自転車}で学校[がっこう]へ行[い]きます。", target:"自転車", ans:"じてんしゃ", opts:["じてんしゃ","じどうしゃ","じてんくるま","じてしゃ"], reverse:false, meaning:"bicycle" },
  { level:"N4", s:"大学[だいがく]で日本[にほん]の文化[ぶんか]を{研究}したい。", target:"研究", ans:"けんきゅう", opts:["けんきゅう","けんきゅ","げんきゅう","けんこう"], reverse:false, meaning:"research" },
  { level:"N4", s:"時間[じかん]が{足りない}。", target:"足りない", ans:"たりない", opts:["たりない","あしりない","そくりない","たしりない"], reverse:false, meaning:"not enough" },
  { level:"N4", s:"駅[えき]に{着きました}。", target:"着きました", ans:"つきました", opts:["つきました","きました","ちゃきました","とどきました"], reverse:false, meaning:"to arrive" },
  { level:"N4", s:"祖母[そぼ]が{病気}になってしまった。", target:"病気", ans:"びょうき", opts:["びょうき","びょうけ","やまいき","びょき"], reverse:false, meaning:"illness" },
  { level:"N4", s:"ここで少[すこ]し{待って}いてください。", target:"待って", ans:"まって", opts:["まって","たいって","もって","まちって"], reverse:false, meaning:"to wait" },
  { level:"N4", s:"彼[かれ]はとても{親切}な人[ひと]です。", target:"親切", ans:"しんせつ", opts:["しんせつ","おやせつ","しんぜつ","したせつ"], reverse:false, meaning:"kind" },
  { level:"N4", s:"{英語}より日本語[にほんご]の方[ほう]が好[す]きです。", target:"英語", ans:"えいご", opts:["えいご","えご","えいごう","いぎりすご"], reverse:false, meaning:"English" },
  { level:"N4", s:"新[あたら]しい{仕事}を探[さが]しています。", target:"仕事", ans:"しごと", opts:["しごと","しじ","つかいごと","しこと"], reverse:false, meaning:"job, work" },
  { level:"N4", s:"{去年}の夏[なつ]、日本[にほん]へ行[い]きました。", target:"去年", ans:"きょねん", opts:["きょねん","さくねん","こねん","きょとし"], reverse:false, meaning:"last year" },
  { level:"N4", s:"この{答え}は間違[まちが]っています。", target:"答え", ans:"こたえ", opts:["こたえ","とうえ","こたい","かいとう"], reverse:false, meaning:"answer" },
  { level:"N4", s:"昨日[きのう]の{夜}は早[はや]く寝[ね]ました。", target:"夜", ans:"よる", opts:["よる","や","ばん","ゆうべ"], reverse:false, meaning:"night" },
  { level:"N4", s:"そろそろ家[いえ]に{帰ります}。", target:"帰ります", ans:"かえります", opts:["かえります","きります","かいります","もどります"], reverse:false, meaning:"to return home" },
  { level:"N4", s:"この寺[てら]はとても{古い}です。", target:"古い", ans:"ふるい", opts:["ふるい","こるい","ふりい","きゅうい"], reverse:false, meaning:"old" },
  { level:"N4", s:"日本[にほん]の{歌}を歌[うた]うのが好[す]きです。", target:"歌", ans:"うた", opts:["うた","か","おんがく","こえ"], reverse:false, meaning:"song" },
  { level:"N4", s:"顔色[かおいろ]が{悪い}ですよ。", target:"悪い", ans:"わるい", opts:["わるい","あくい","わろい","にがい"], reverse:false, meaning:"bad" },
  { level:"N4", s:"{今週}は忙[いそが]しいです。", target:"今週", ans:"こんしゅう", opts:["こんしゅう","いましゅう","こんしゅ","きんしゅう"], reverse:false, meaning:"this week" },
  { level:"N4", s:"{教室}で先生[せんせい]を待[ま]っています。", target:"教室", ans:"きょうしつ", opts:["きょうしつ","きょうしち","こうしつ","きょうへや"], reverse:false, meaning:"classroom" },
  { level:"N4", s:"今日[きょう]は{風}が強[つよ]い。", target:"風", ans:"かぜ", opts:["かぜ","ふう","かぜん","あらし"], reverse:false, meaning:"wind" },
  { level:"N4", s:"{黒い}猫[ねこ]を飼[か]っています。", target:"黒い", ans:"くろい", opts:["くろい","こくい","くらい","しろい"], reverse:false, meaning:"black" },
  { level:"N4", s:"春[はる]になったら{花見}をしましょう。", target:"花見", ans:"はなみ", opts:["はなみ","かみ","はなけん","かけん"], reverse:false, meaning:"cherry blossom viewing" },
  { level:"N4", s:"姉[あね]に{赤ちゃん}が生[う]まれました。", target:"赤ちゃん", ans:"あかちゃん", opts:["あかちゃん","せきちゃん","あこちゃん","あかんぼう"], reverse:false, meaning:"baby" },
  { level:"N4", s:"{青い}シャツを着[き]ている人[ひと]が兄[あに]です。", target:"青い", ans:"あおい", opts:["あおい","せいい","あかい","あわい"], reverse:false, meaning:"blue" },
  { level:"N4", s:"駅[えき]の前[まえ]に新[あたら]しい{映画館}ができた。", target:"映画館", ans:"えいがかん", opts:["えいがかん","えいがやかた","えいかん","えいがけん"], reverse:false, meaning:"movie theater" },
  { level:"N4", s:"どの{色}が一番[いちばん]好[す]きですか。", target:"色", ans:"いろ", opts:["いろ","しき","しょく","がら"], reverse:false, meaning:"color" },
  { level:"N4", s:"新[あたら]しい{洋服}を買[か]いに行[い]く。", target:"洋服", ans:"ようふく", opts:["ようふく","よふく","ようぶく","わふく"], reverse:false, meaning:"clothes" },
  { level:"N4", s:"{夕方}から雨[あめ]が降[ふ]るそうです。", target:"夕方", ans:"ゆうがた", opts:["ゆうがた","ゆうほう","せきがた","ゆがた"], reverse:false, meaning:"evening" },
  { level:"N4", s:"{土曜日}に映画[えいが]を見[み]に行[い]きませんか。", target:"土曜日", ans:"どようび", opts:["どようび","どようひ","つちようび","どうようび"], reverse:false, meaning:"Saturday" },
  { level:"N4", s:"何[なに]か{飲み物}はいかがですか。", target:"飲み物", ans:"のみもの", opts:["のみもの","いんもの","のみぶつ","たべもの"], reverse:false, meaning:"drink, beverage" },
  { level:"N4", s:"{牛肉}より魚[さかな]の方[ほう]が好[す]きだ。", target:"牛肉", ans:"ぎゅうにく", opts:["ぎゅうにく","うしにく","ぎゅにく","ぶたにく"], reverse:false, meaning:"beef" },
  { level:"N4", s:"昼[ひる]は大学[だいがく]の{食堂}で食[た]べます。", target:"食堂", ans:"しょくどう", opts:["しょくどう","しょくとう","しょうどう","くいどう"], reverse:false, meaning:"cafeteria" },
  { level:"N4", s:"朝[あさ]、{鳥}の声[こえ]で目[め]が覚[さ]めた。", target:"鳥", ans:"とり", opts:["とり","ちょう","つばさ","ことり"], reverse:false, meaning:"bird" },
  { level:"N4", s:"{昼休み}に公園[こうえん]へ行[い]きました。", target:"昼休み", ans:"ひるやすみ", opts:["ひるやすみ","ちゅうやすみ","ひるきゅう","はんやすみ"], reverse:false, meaning:"lunch break" },
  { level:"N4", s:"{お茶}でも飲[の]みませんか。", target:"お茶", ans:"おちゃ", opts:["おちゃ","おさ","おちや","こうちゃ"], reverse:false, meaning:"tea" },
  { level:"N4", s:"市場[いちば]で新鮮[しんせん]な{魚}を買[か]った。", target:"魚", ans:"さかな", opts:["さかな","ぎょ","にく","かい"], reverse:false, meaning:"fish" },
  { level:"N4", s:"{犬}を二匹[にひき]飼[か]っています。", target:"犬", ans:"いぬ", opts:["いぬ","けん","こいぬ","ねこ"], reverse:false, meaning:"dog" },
  { level:"N4", s:"{妹}は高校生[こうこうせい]です。", target:"妹", ans:"いもうと", opts:["いもうと","おとうと","あね","まい"], reverse:false, meaning:"younger sister" },
  { level:"N4", s:"{姉}は銀行[ぎんこう]で働[はたら]いています。", target:"姉", ans:"あね", opts:["あね","あに","いもうと","し"], reverse:false, meaning:"elder sister" },
  { level:"N4", s:"この{漢字}の書[か]き方[かた]を教[おし]えてください。", target:"漢字", ans:"かんじ", opts:["かんじ","かんし","はんじ","かんじつ"], reverse:false, meaning:"kanji" },
  // N4 reverse (kana -> kanji)
  { level:"N4", s:"毎日[まいにち]、日本語[にほんご]を{べんきょう}しています。", target:"べんきょう", ans:"勉強", opts:["勉強","勉張","免強","勉京"], reverse:true, meaning:"study" },
  { level:"N4", s:"日曜日[にちようび]に部屋[へや]を{そうじ}しました。", target:"そうじ", ans:"掃除", opts:["掃除","掃徐","帰除","掃余"], reverse:true, meaning:"cleaning" },
  { level:"N4", s:"駅[えき]まで自転車[じてんしゃ]で{はしって}行[い]った。", target:"はしって", ans:"走って", opts:["走って","起って","足って","徒って"], reverse:true, meaning:"to run" },
  { level:"N4", s:"この漢字[かんじ]の{いみ}が分[わ]かりません。", target:"いみ", ans:"意味", opts:["意味","意昧","音味","意未"], reverse:true, meaning:"meaning" },
  { level:"N4", s:"母[はは]の手作[てづく]りの料理[りょうり]は{あじ}がいい。", target:"あじ", ans:"味", opts:["味","昧","未","末"], reverse:true, meaning:"flavor" },
  { level:"N4", s:"来週[らいしゅう]{しけん}があるので緊張[きんちょう]しています。", target:"しけん", ans:"試験", opts:["試験","式験","試検","訊験"], reverse:true, meaning:"exam" },
  { level:"N4", s:"友達[ともだち]に本[ほん]を{かりました}。", target:"かりました", ans:"借りました", opts:["借りました","貸りました","昔りました","惜りました"], reverse:true, meaning:"to borrow" },
  { level:"N4", s:"寒[さむ]くなったので{ふゆ}が近[ちか]い。", target:"ふゆ", ans:"冬", opts:["冬","夏","終","各"], reverse:true, meaning:"winter" },
  { level:"N4", s:"{あたま}が痛[いた]いので休[やす]みます。", target:"あたま", ans:"頭", opts:["頭","顔","題","豆"], reverse:true, meaning:"head" },
  { level:"N4", s:"毎日[まいにち]{うんどう}しています。", target:"うんどう", ans:"運動", opts:["運動","運働","連動","運勤"], reverse:true, meaning:"exercise" },
  { level:"N4", s:"{かぞく}と旅行[りょこう]に行[い]きました。", target:"かぞく", ans:"家族", opts:["家族","家続","家俗","嫁族"], reverse:true, meaning:"family" },
  { level:"N4", s:"{じしょ}で言葉[ことば]を調[しら]べます。", target:"じしょ", ans:"辞書", opts:["辞書","辞署","持書","自書"], reverse:true, meaning:"dictionary" },
  { level:"N4", s:"{あき}は涼[すず]しくて好[す]きです。", target:"あき", ans:"秋", opts:["秋","穂","愁","秒"], reverse:true, meaning:"autumn" },
  { level:"N4", s:"変[へん]な{おと}が聞[き]こえます。", target:"おと", ans:"音", opts:["音","意","暗","立"], reverse:true, meaning:"sound" },
  { level:"N4", s:"{はる}になると桜[さくら]が咲[さ]きます。", target:"はる", ans:"春", opts:["春","晴","青","奏"], reverse:true, meaning:"spring" },
  { level:"N4", s:"もっと{ちから}を入[い]れてください。", target:"ちから", ans:"力", opts:["力","刀","九","方"], reverse:true, meaning:"power, strength" },
  { level:"N4", s:"食後[しょくご]にこの{くすり}を飲[の]んでください。", target:"くすり", ans:"薬", opts:["薬","楽","草","菜"], reverse:true, meaning:"medicine" },
  { level:"N4", s:"今日[きょう]は{ようじ}があって行[い]けません。", target:"ようじ", ans:"用事", opts:["用事","幼児","要事","用字"], reverse:true, meaning:"errand, business" },
  { level:"N4", s:"{て}をよく洗[あら]ってください。", target:"て", ans:"手", opts:["手","毛","千","于"], reverse:true, meaning:"hand" },
  { level:"N4", s:"{こころ}から感謝[かんしゃ]しています。", target:"こころ", ans:"心", opts:["心","必","思","念"], reverse:true, meaning:"heart, mind" },
  { level:"N4", s:"駅前[えきまえ]に新[あたら]しい{みせ}ができた。", target:"みせ", ans:"店", opts:["店","占","庁","席"], reverse:true, meaning:"shop, store" },
  { level:"N4", s:"明日[あした]の{あさ}、電話[でんわ]します。", target:"あさ", ans:"朝", opts:["朝","潮","幹","乾"], reverse:true, meaning:"morning" },
  { level:"N4", s:"この{みち}をまっすぐ行[い]ってください。", target:"みち", ans:"道", opts:["道","首","通","導"], reverse:true, meaning:"road, street" },
  { level:"N4", s:"{かみ}に名前[なまえ]を書[か]いてください。", target:"かみ", ans:"紙", opts:["紙","神","髪","絹"], reverse:true, meaning:"paper" },

  // ===================== N3 =====================
  { level:"N3", s:"電車[でんしゃ]に{乗っている}間[あいだ]、ずっと本[ほん]を読[よ]んでいました。", target:"乗っている", ans:"のっている", opts:["のっている","ねている","のこっている","はしっている"], reverse:false, meaning:"to ride" },
  { level:"N3", s:"来年[らいねん]の選挙[せんきょ]で新[あたら]しい{政治}が始[はじ]まる。", target:"政治", ans:"せいじ", opts:["せいじ","せいち","しょうじ","せいぎ"], reverse:false, meaning:"politics" },
  { level:"N3", s:"国民[こくみん]の{意見}を大切[たいせつ]にするべきだ。", target:"意見", ans:"いけん", opts:["いけん","いげん","いっけん","いみ"], reverse:false, meaning:"opinion" },
  { level:"N3", s:"この二[ふた]つの{関係}を説明[せつめい]してください。", target:"関係", ans:"かんけい", opts:["かんけい","かんげい","かんかい","けんけい"], reverse:false, meaning:"relation" },
  { level:"N3", s:"会議[かいぎ]で来月[らいげつ]の予定[よてい]を{決めました}。", target:"決めました", ans:"きめました", opts:["きめました","けつめました","しめました","かめました"], reverse:false, meaning:"to decide" },
  { level:"N3", s:"この問題[もんだい]は{複雑}なのでよく考[かんが]えよう。", target:"複雑", ans:"ふくざつ", opts:["ふくざつ","ふくすう","ふくし","ふくそう"], reverse:false, meaning:"complicated" },
  { level:"N3", s:"最近[さいきん]、日本[にほん]の{経済}は変化[へんか]している。", target:"経済", ans:"けいざい", opts:["けいざい","けいさい","きょうざい","けいえい"], reverse:false, meaning:"economy" },
  { level:"N3", s:"先生[せんせい]の{説明}はとても分[わ]かりやすかった。", target:"説明", ans:"せつめい", opts:["せつめい","せつあき","せいめい","せきめい"], reverse:false, meaning:"explanation" },
  { level:"N3", s:"約束[やくそく]の時間[じかん]に{遅れて}しまい、すみません。", target:"遅れて", ans:"おくれて", opts:["おくれて","わすれて","はなれて","つかれて"], reverse:false, meaning:"to be late" },
  { level:"N3", s:"彼女[かのじょ]は毎朝[まいあさ]、公園[こうえん]を{散歩}しています。", target:"散歩", ans:"さんぽ", opts:["さんぽ","さんぼ","ちらほ","さんふ"], reverse:false, meaning:"a walk, stroll" },
  { level:"N3", s:"レポートの{締め切り}は金曜日[きんようび]です。", target:"締め切り", ans:"しめきり", opts:["しめきり","しまきり","ていきり","しめぎり"], reverse:false, meaning:"deadline" },
  { level:"N3", s:"この件[けん]について{相談}したいです。", target:"相談", ans:"そうだん", opts:["そうだん","しょうだん","あいだん","そうたん"], reverse:false, meaning:"consultation" },
  { level:"N3", s:"事故[じこ]の{原因}はまだ分[わ]かっていない。", target:"原因", ans:"げんいん", opts:["げんいん","げいいん","がんいん","げにん"], reverse:false, meaning:"cause" },
  { level:"N3", s:"新[あたら]しい規則[きそく]に{反対}する人[ひと]が多[おお]い。", target:"反対", ans:"はんたい", opts:["はんたい","はんつい","へんたい","はんだい"], reverse:false, meaning:"opposition" },
  { level:"N3", s:"試合[しあい]に{勝つ}ために毎日[まいにち]練習[れんしゅう]した。", target:"勝つ", ans:"かつ", opts:["かつ","しょうつ","まつ","がつ"], reverse:false, meaning:"to win" },
  { level:"N3", s:"彼[かれ]は約束[やくそく]を{守る}人[ひと]です。", target:"守る", ans:"まもる", opts:["まもる","しゅる","もりる","かえる"], reverse:false, meaning:"to protect, keep" },
  { level:"N3", s:"難[むずか]しい漢字[かんじ]を{覚える}のは大変[たいへん]だ。", target:"覚える", ans:"おぼえる", opts:["おぼえる","かくえる","さめる","おもえる"], reverse:false, meaning:"to memorize" },
  { level:"N3", s:"この道具[どうぐ]の{使い方}を教[おし]えてください。", target:"使い方", ans:"つかいかた", opts:["つかいかた","しようかた","つかいほう","しかた"], reverse:false, meaning:"how to use" },
  { level:"N3", s:"友達[ともだち]を駅[えき]まで{迎え}に行[い]きました。", target:"迎え", ans:"むかえ", opts:["むかえ","げいえ","むけえ","まちえ"], reverse:false, meaning:"to meet, welcome" },
  { level:"N3", s:"熱[ねつ]があるので学校[がっこう]を{欠席}します。", target:"欠席", ans:"けっせき", opts:["けっせき","けつせき","かんせき","けっぱき"], reverse:false, meaning:"absence" },
  { level:"N3", s:"最近[さいきん]、仕事[しごと]に{慣れて}きました。", target:"慣れて", ans:"なれて", opts:["なれて","かんれて","はなれて","われて"], reverse:false, meaning:"to get used to" },
  { level:"N3", s:"財布[さいふ]を{盗まれて}しまった。", target:"盗まれて", ans:"ぬすまれて", opts:["ぬすまれて","とうまれて","おかまれて","こまれて"], reverse:false, meaning:"to be stolen" },
  { level:"N3", s:"景色[けしき]がとても{美しい}山[やま]でした。", target:"美しい", ans:"うつくしい", opts:["うつくしい","うるわしい","うれしい","たのしい"], reverse:false, meaning:"beautiful" },
  { level:"N3", s:"社長[しゃちょう]が新[あたら]しい方針[ほうしん]を{発表}した。", target:"発表", ans:"はっぴょう", opts:["はっぴょう","はつひょう","はっぴゅう","はつぴょう"], reverse:false, meaning:"announcement" },
  { level:"N3", s:"彼[かれ]の話[はなし]は{疑わしい}と思[おも]う。", target:"疑わしい", ans:"うたがわしい", opts:["うたがわしい","ぎわしい","まぎらわしい","わずらわしい"], reverse:false, meaning:"doubtful" },
  { level:"N3", s:"火事[かじ]で家[いえ]が{倒れて}しまった。", target:"倒れて", ans:"たおれて", opts:["たおれて","とうれて","こわれて","われて"], reverse:false, meaning:"to collapse" },
  { level:"N3", s:"この薬[くすり]を飲[の]めば頭[あたま]の{痛み}が消[き]える。", target:"痛み", ans:"いたみ", opts:["いたみ","つうみ","やみ","なやみ"], reverse:false, meaning:"pain" },
  { level:"N3", s:"彼[かれ]は困[こま]っている人[ひと]を{助けた}。", target:"助けた", ans:"たすけた", opts:["たすけた","じょけた","すけた","たしけた"], reverse:false, meaning:"to help" },
  { level:"N3", s:"地球[ちきゅう]の{環境}を守[まも]ることが大切[たいせつ]だ。", target:"環境", ans:"かんきょう", opts:["かんきょう","かんけい","けんきょう","かんきょ"], reverse:false, meaning:"environment" },
  { level:"N3", s:"テレビは子供[こども]に大[おお]きな{影響}を与[あた]える。", target:"影響", ans:"えいきょう", opts:["えいきょう","えいこう","けいきょう","えいぎょう"], reverse:false, meaning:"influence" },
  { level:"N3", s:"海外[かいがい]で働[はたら]いた{経験}があります。", target:"経験", ans:"けいけん", opts:["けいけん","けいげん","きょうけん","けいこん"], reverse:false, meaning:"experience" },
  { level:"N3", s:"インターネットで{情報}を集[あつ]めた。", target:"情報", ans:"じょうほう", opts:["じょうほう","じょうぼう","せいほう","じょほう"], reverse:false, meaning:"information" },
  { level:"N3", s:"旅行[りょこう]の{準備}はもう終[お]わりましたか。", target:"準備", ans:"じゅんび", opts:["じゅんび","じゅんぴ","しゅんび","じゅび"], reverse:false, meaning:"preparation" },
  { level:"N3", s:"日本[にほん]に来[く]る観光客[かんこうきゃく]が{増えて}いる。", target:"増えて", ans:"ふえて", opts:["ふえて","ぞうえて","まして","こえて"], reverse:false, meaning:"to increase" },
  { level:"N3", s:"子供[こども]の数[かず]が{減って}きている。", target:"減って", ans:"へって", opts:["へって","げんって","めって","ちって"], reverse:false, meaning:"to decrease" },
  { level:"N3", s:"値段[ねだん]を{比べる}のは大事[だいじ]だ。", target:"比べる", ans:"くらべる", opts:["くらべる","ひべる","しらべる","ならべる"], reverse:false, meaning:"to compare" },
  { level:"N3", s:"五年間[ごねんかん]、日本語[にほんご]の勉強[べんきょう]を{続けて}います。", target:"続けて", ans:"つづけて", opts:["つづけて","ぞくけて","つずけて","つとめて"], reverse:false, meaning:"to continue" },
  { level:"N3", s:"車[くるま]に{注意}してください。", target:"注意", ans:"ちゅうい", opts:["ちゅうい","ちゅい","そそい","しゅうい"], reverse:false, meaning:"attention, caution" },
  { level:"N3", s:"レストランを{予約}しました。", target:"予約", ans:"よやく", opts:["よやく","ようやく","よてい","やくそく"], reverse:false, meaning:"reservation" },
  { level:"N3", s:"駅[えき]まで{案内}します。", target:"案内", ans:"あんない", opts:["あんない","あんうち","けんない","あんがい"], reverse:false, meaning:"guidance" },
  { level:"N3", s:"飛行機[ひこうき]は九時[くじ]に{到着}します。", target:"到着", ans:"とうちゃく", opts:["とうちゃく","とちゃく","どうちゃく","とうつき"], reverse:false, meaning:"arrival" },
  { level:"N3", s:"どうぞ{遠慮}しないで食[た]べてください。", target:"遠慮", ans:"えんりょ", opts:["えんりょ","えんろ","おんりょ","えんりょう"], reverse:false, meaning:"restraint, reserve" },
  { level:"N3", s:"痛[いた]みを{我慢}して試合[しあい]に出[で]た。", target:"我慢", ans:"がまん", opts:["がまん","われまん","がばん","かまん"], reverse:false, meaning:"endurance" },
  { level:"N3", s:"実験[じっけん]は{成功}した。", target:"成功", ans:"せいこう", opts:["せいこう","せいくう","じょうこう","せいごう"], reverse:false, meaning:"success" },
  { level:"N3", s:"{失敗}を恐[おそ]れないでください。", target:"失敗", ans:"しっぱい", opts:["しっぱい","しつばい","しっけい","しつぼう"], reverse:false, meaning:"failure" },
  { level:"N3", s:"{険しい}山道[やまみち]を登[のぼ]った。", target:"険しい", ans:"けわしい", opts:["けわしい","けんしい","きびしい","あやしい"], reverse:false, meaning:"steep" },
  { level:"N3", s:"この地方[ちほう]では雪[ゆき]は{珍しい}。", target:"珍しい", ans:"めずらしい", opts:["めずらしい","ちんしい","むずかしい","すばらしい"], reverse:false, meaning:"rare" },
  { level:"N3", s:"あの先生[せんせい]はとても{厳しい}。", target:"厳しい", ans:"きびしい", opts:["きびしい","げんしい","くやしい","けわしい"], reverse:false, meaning:"strict" },
  { level:"N3", s:"日本[にほん]は多[おお]くの国[くに]と{貿易}している。", target:"貿易", ans:"ぼうえき", opts:["ぼうえき","ぼえき","むえき","ぼうい"], reverse:false, meaning:"trade" },
  { level:"N3", s:"明日[あした]、会社[かいしゃ]の{面接}があります。", target:"面接", ans:"めんせつ", opts:["めんせつ","めんぜつ","めんせち","おもせつ"], reverse:false, meaning:"interview" },
  { level:"N3", s:"この店[みせ]は夜[よる]十時[じゅうじ]まで{営業}している。", target:"営業", ans:"えいぎょう", opts:["えいぎょう","えいごう","えぎょう","えいきょう"], reverse:false, meaning:"business (operating)" },
  { level:"N3", s:"棚[たな]に新[あたら]しい{商品}が並[なら]んでいる。", target:"商品", ans:"しょうひん", opts:["しょうひん","しょうもの","そうひん","しょひん"], reverse:false, meaning:"merchandise" },
  { level:"N3", s:"この{製品}は品質[ひんしつ]がいい。", target:"製品", ans:"せいひん", opts:["せいひん","せひん","せいしん","せいびん"], reverse:false, meaning:"manufactured product" },
  { level:"N3", s:"このチケットは駅[えき]でも{販売}している。", target:"販売", ans:"はんばい", opts:["はんばい","はんまい","ばんばい","はんうり"], reverse:false, meaning:"sales, selling" },
  { level:"N3", s:"学生[がくせい]なら{割引}が受[う]けられます。", target:"割引", ans:"わりびき", opts:["わりびき","わりひき","かつびき","わりいん"], reverse:false, meaning:"discount" },
  { level:"N3", s:"{給料}が上[あ]がってうれしい。", target:"給料", ans:"きゅうりょう", opts:["きゅうりょう","きゅうろう","きゅりょう","きゅうりょ"], reverse:false, meaning:"salary" },
  { level:"N3", s:"今日[きょう]も{残業}で帰[かえ]りが遅[おそ]くなった。", target:"残業", ans:"ざんぎょう", opts:["ざんぎょう","ざんごう","のこぎょう","さんぎょう"], reverse:false, meaning:"overtime work" },
  { level:"N3", s:"{通勤}に一時間[いちじかん]かかります。", target:"通勤", ans:"つうきん", opts:["つうきん","つうごん","とおきん","つきん"], reverse:false, meaning:"commuting" },
  { level:"N3", s:"電車[でんしゃ]が止[と]まって{遅刻}してしまった。", target:"遅刻", ans:"ちこく", opts:["ちこく","おそこく","ちごく","じこく"], reverse:false, meaning:"tardiness" },
  { level:"N3", s:"駅[えき]に着[つ]いたら{連絡}してください。", target:"連絡", ans:"れんらく", opts:["れんらく","れんかく","れらく","れんそく"], reverse:false, meaning:"contact" },
  { level:"N3", s:"友達[ともだち]との{約束}を忘[わす]れていた。", target:"約束", ans:"やくそく", opts:["やくそく","やくぞく","よやく","けいやく"], reverse:false, meaning:"promise" },
  { level:"N3", s:"それは{冗談}ですよね。", target:"冗談", ans:"じょうだん", opts:["じょうだん","じょだん","そうだん","じょうたん"], reverse:false, meaning:"joke" },
  { level:"N3", s:"夜中[よなか]に大[おお]きな音[おと]を出[だ]すと近所[きんじょ]の{迷惑}になる。", target:"迷惑", ans:"めいわく", opts:["めいわく","まいわく","めわく","めいこん"], reverse:false, meaning:"nuisance, trouble" },
  { level:"N3", s:"夕食[ゆうしょく]の{用意}ができましたよ。", target:"用意", ans:"ようい", opts:["ようい","ようき","もちい","よい"], reverse:false, meaning:"getting ready" },
  { level:"N3", s:"体[からだ]の{具合}はどうですか。", target:"具合", ans:"ぐあい", opts:["ぐあい","ぐごう","くあい","つごう"], reverse:false, meaning:"condition (health)" },
  { level:"N3", s:"{都合}が悪[わる]ければ日[ひ]を変[か]えましょう。", target:"都合", ans:"つごう", opts:["つごう","とごう","つあい","ぐあい"], reverse:false, meaning:"convenience, circumstances" },
  { level:"N3", s:"彼[かれ]は{熱心}に日本語[にほんご]を勉強[べんきょう]している。", target:"熱心", ans:"ねっしん", opts:["ねっしん","ねつしん","あつしん","ねっこころ"], reverse:false, meaning:"enthusiastic" },
  { level:"N3", s:"妹[いもうと]は数学[すうがく]が{得意}です。", target:"得意", ans:"とくい", opts:["とくい","どくい","とくぎ","えとく"], reverse:false, meaning:"good at" },
  { level:"N3", s:"私[わたし]は人前[ひとまえ]で話[はな]すのが{苦手}だ。", target:"苦手", ans:"にがて", opts:["にがて","くて","くるて","にがしゅ"], reverse:false, meaning:"bad at, weak point" },
  { level:"N3", s:"弟[おとうと]は新[あたら]しいゲームに{夢中}だ。", target:"夢中", ans:"むちゅう", opts:["むちゅう","ゆめじゅう","むじゅう","ぼっちゅう"], reverse:false, meaning:"absorbed in, crazy about" },
  { level:"N3", s:"その映画[えいが]を見[み]て{感動}した。", target:"感動", ans:"かんどう", opts:["かんどう","かんとう","がんどう","かんどん"], reverse:false, meaning:"deeply moved" },
  { level:"N3", s:"十年後[じゅうねんご]の自分[じぶん]を{想像}してみた。", target:"想像", ans:"そうぞう", opts:["そうぞう","しょうぞう","そぞう","そうじょう"], reverse:false, meaning:"imagination" },
  { level:"N3", s:"問題[もんだい]はまだ{解決}していない。", target:"解決", ans:"かいけつ", opts:["かいけつ","げけつ","かいかつ","かいけい"], reverse:false, meaning:"solution, settlement" },
  { level:"N3", s:"あの店[みせ]はアルバイトを{募集}している。", target:"募集", ans:"ぼしゅう", opts:["ぼしゅう","ぼうしゅう","もしゅう","ぼしゅ"], reverse:false, meaning:"recruitment" },
  { level:"N3", s:"道[みち]が{渋滞}していて、バスが遅[おく]れた。", target:"渋滞", ans:"じゅうたい", opts:["じゅうたい","しぶたい","じゅたい","じゅうだい"], reverse:false, meaning:"traffic jam" },
  { level:"N3", s:"朝[あさ]の電車[でんしゃ]はいつも{混んで}いる。", target:"混んで", ans:"こんで", opts:["こんで","まぜんで","こみんで","くんで"], reverse:false, meaning:"to be crowded" },
  { level:"N3", s:"転[ころ]んでズボンが{破れて}しまった。", target:"破れて", ans:"やぶれて", opts:["やぶれて","はれて","わられて","こわれて"], reverse:false, meaning:"to be torn" },
  { level:"N3", s:"白[しろ]いシャツが{汚れて}しまった。", target:"汚れて", ans:"よごれて", opts:["よごれて","きたなれて","おごれて","よぼれて"], reverse:false, meaning:"to get dirty" },
  // N3 reverse (kana -> kanji)
  { level:"N3", s:"電車[でんしゃ]に{のっている}間[あいだ]、本[ほん]を読[よ]んでいた。", target:"のっている", ans:"乗っている", opts:["乗っている","載っている","残っている","昇っている"], reverse:true, meaning:"to ride" },
  { level:"N3", s:"この件[けん]について{そうだん}があります。", target:"そうだん", ans:"相談", opts:["相談","想談","相段","双談"], reverse:true, meaning:"consultation" },
  { level:"N3", s:"約束[やくそく]の時間[じかん]に{おくれて}すみません。", target:"おくれて", ans:"遅れて", opts:["遅れて","送れて","返れて","逃れて"], reverse:true, meaning:"to be late" },
  { level:"N3", s:"難[むずか]しい漢字[かんじ]を{おぼえる}努力[どりょく]をしている。", target:"おぼえる", ans:"覚える", opts:["覚える","党える","賞える","営える"], reverse:true, meaning:"to memorize" },
  { level:"N3", s:"事故[じこ]の{げんいん}を調[しら]べています。", target:"げんいん", ans:"原因", opts:["原因","元因","源因","原困"], reverse:true, meaning:"cause" },
  { level:"N3", s:"この計画[けいかく]に{はんたい}する人[ひと]が多[おお]い。", target:"はんたい", ans:"反対", opts:["反対","反村","返対","反刻"], reverse:true, meaning:"opposition" },
  { level:"N3", s:"毎朝[まいあさ]、犬[いぬ]と一緒[いっしょ]に{さんぽ}します。", target:"さんぽ", ans:"散歩", opts:["散歩","散步","参歩","散渉"], reverse:true, meaning:"a walk" },
  { level:"N3", s:"レポートの{しめきり}に間[ま]に合[あ]った。", target:"しめきり", ans:"締め切り", opts:["締め切り","閉め切り","絞め切り","占め切り"], reverse:true, meaning:"deadline" },
  { level:"N3", s:"この問題[もんだい]は{ふくざつ}すぎる。", target:"ふくざつ", ans:"複雑", opts:["複雑","復雑","複難","復難"], reverse:true, meaning:"complicated" },
  { level:"N3", s:"仕事[しごと]に少[すこ]しずつ{なれて}きた。", target:"なれて", ans:"慣れて", opts:["慣れて","憎れて","憤れて","貫れて"], reverse:true, meaning:"to get used to" },
  { level:"N3", s:"友達[ともだち]を駅[えき]まで{むかえ}に行[い]く。", target:"むかえ", ans:"迎え", opts:["迎え","仰え","抑え","却え"], reverse:true, meaning:"to meet, welcome" },
  { level:"N3", s:"財布[さいふ]を{ぬすまれた}。", target:"ぬすまれた", ans:"盗まれた", opts:["盗まれた","盛まれた","監まれた","塗まれた"], reverse:true, meaning:"to be stolen" },
  { level:"N3", s:"早起[はやお]きの{しゅうかん}をつけたい。", target:"しゅうかん", ans:"習慣", opts:["習慣","週間","習貫","修慣"], reverse:true, meaning:"habit" },
  { level:"N3", s:"日本[にほん]の文化[ぶんか]に{きょうみ}があります。", target:"きょうみ", ans:"興味", opts:["興味","興未","共味","強味"], reverse:true, meaning:"interest" },
  { level:"N3", s:"山[やま]の上[うえ]からの{けしき}は最高[さいこう]だった。", target:"けしき", ans:"景色", opts:["景色","景職","影色","景識"], reverse:true, meaning:"scenery" },
  { level:"N3", s:"この{ねだん}は高[たか]すぎる。", target:"ねだん", ans:"値段", opts:["値段","値団","直段","値談"], reverse:true, meaning:"price" },
  { level:"N3", s:"電話[でんわ]したが{るす}だった。", target:"るす", ans:"留守", opts:["留守","留主","流守","留字"], reverse:true, meaning:"absence from home" },
  { level:"N3", s:"週末[しゅうまつ]の{よてい}を教[おし]えてください。", target:"よてい", ans:"予定", opts:["予定","予庭","矛定","預定"], reverse:true, meaning:"plan, schedule" },
  { level:"N3", s:"その知[し]らせを聞[き]いて{かなしい}気持[きも]ちになった。", target:"かなしい", ans:"悲しい", opts:["悲しい","非しい","悔しい","怖しい"], reverse:true, meaning:"sad" },
  { level:"N3", s:"エレベーターが{こしょう}している。", target:"こしょう", ans:"故障", opts:["故障","故章","枯障","故彰"], reverse:true, meaning:"breakdown" },
  { level:"N3", s:"この川[かわ]で泳[およ]ぐのは{きけん}だ。", target:"きけん", ans:"危険", opts:["危険","危検","机険","危剣"], reverse:true, meaning:"danger" },
  { level:"N3", s:"東京[とうきょう]での{せいかつ}に慣[な]れた。", target:"せいかつ", ans:"生活", opts:["生活","性活","生括","正活"], reverse:true, meaning:"life, living" },
  { level:"N3", s:"{しょうらい}は医者[いしゃ]になりたい。", target:"しょうらい", ans:"将来", opts:["将来","招来","将米","奨来"], reverse:true, meaning:"future" },
  { level:"N3", s:"昨夜[ゆうべ]、変[へん]な{ゆめ}を見[み]た。", target:"ゆめ", ans:"夢", opts:["夢","霧","蒸","夜"], reverse:true, meaning:"dream" },
  { level:"N3", s:"明日[あした]の{しあい}に勝[か]ちたい。", target:"しあい", ans:"試合", opts:["試合","試会","式合","私合"], reverse:true, meaning:"match, game" },
  { level:"N3", s:"外[そと]の{ようす}を見[み]てきます。", target:"ようす", ans:"様子", opts:["様子","用子","洋子","要子"], reverse:true, meaning:"state, appearance" },
  { level:"N3", s:"遅[おく]れた{りゆう}を説明[せつめい]してください。", target:"りゆう", ans:"理由", opts:["理由","利由","理油","里由"], reverse:true, meaning:"reason" },
  { level:"N3", s:"雨[あめ]の{ばあい}は中止[ちゅうし]です。", target:"ばあい", ans:"場合", opts:["場合","場会","馬合","揚合"], reverse:true, meaning:"case, situation" },
  { level:"N3", s:"{かんじょう}を顔[かお]に出[だ]さないようにした。", target:"かんじょう", ans:"感情", opts:["感情","勘定","感清","惑情"], reverse:true, meaning:"emotion" },
  { level:"N3", s:"祖父[そふ]は来週[らいしゅう]{たいいん}する予定[よてい]だ。", target:"たいいん", ans:"退院", opts:["退院","対院","隊院","待院"], reverse:true, meaning:"leaving hospital" },
  { level:"N3", s:"学校[がっこう]の{きそく}を守[まも]らなければならない。", target:"きそく", ans:"規則", opts:["規則","規測","現則","規側"], reverse:true, meaning:"rules" },
  { level:"N3", s:"リーダーには重[おも]い{せきにん}がある。", target:"せきにん", ans:"責任", opts:["責任","積任","責認","貴任"], reverse:true, meaning:"responsibility" },
  { level:"N3", s:"駅前[えきまえ]で道路[どうろ]の{こうじ}をしている。", target:"こうじ", ans:"工事", opts:["工事","交事","攻事","功事"], reverse:true, meaning:"construction" },
  { level:"N3", s:"日本[にほん]は車[くるま]を多[おお]く{ゆしゅつ}している。", target:"ゆしゅつ", ans:"輸出", opts:["輸出","輪出","輸山","愉出"], reverse:true, meaning:"export" },
  { level:"N3", s:"{ゆき}で電車[でんしゃ]が止[と]まってしまった。", target:"ゆき", ans:"雪", opts:["雪","雲","雷","電"], reverse:true, meaning:"snow" }
];
